<div id="loader" class="loader hidden">
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; display: block; shape-rendering: auto;" width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <circle cx="50" cy="50" fill="none" stroke="#000000" stroke-width="13" r="37" stroke-dasharray="174.35839227423352 60.119464091411174">
      <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1.6666666666666667s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
    </circle>
    <!-- [ldio] generated by https://loading.io/ -->
  </svg>

  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; display: none;" width="237px" height="237px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <defs>
      <filter id="ldio-vl8yje91c5f-filter" x="-100%" y="-100%" width="300%" height="300%" color-interpolation-filters="sRGB">
        <feGaussianBlur in="SourceGraphic" stdDeviation="6"></feGaussianBlur>
        <feComponentTransfer result="cutoff">
          <feFuncA type="table" tableValues="0 0 0 0 0 0 1 1 1 1 1"></feFuncA>
        </feComponentTransfer>
      </filter>
    </defs>
    <g filter="url(#ldio-vl8yje91c5f-filter)">
      <g transform="translate(50 50)">
        <g>
          <circle cx="23" cy="0" r="5" fill="#42009c">
            <animate attributeName="r" keyTimes="0;0.5;1" values="9;21;9" dur="7.692307692307692s" repeatCount="indefinite" begin="-0.13s"></animate>
          </circle>
          <animateTransform attributeName="transform" type="rotate" keyTimes="0;1" values="0;360" dur="7.692307692307692s" repeatCount="indefinite" begin="0s"></animateTransform>
        </g>
      </g>
      <g transform="translate(50 50)">
        <g>
          <circle cx="23" cy="0" r="5" fill="#730eb3">
            <animate attributeName="r" keyTimes="0;0.5;1" values="9;21;9" dur="3.846153846153846s" repeatCount="indefinite" begin="-0.10400000000000001s"></animate>
          </circle>
          <animateTransform attributeName="transform" type="rotate" keyTimes="0;1" values="0;360" dur="3.846153846153846s" repeatCount="indefinite" begin="-0.026000000000000002s"></animateTransform>
        </g>
      </g>
      <g transform="translate(50 50)">
        <g>
          <circle cx="23" cy="0" r="5" fill="#ef5509">
            <animate attributeName="r" keyTimes="0;0.5;1" values="9;21;9" dur="2.564102564102564s" repeatCount="indefinite" begin="-0.078s"></animate>
          </circle>
          <animateTransform attributeName="transform" type="rotate" keyTimes="0;1" values="0;360" dur="2.564102564102564s" repeatCount="indefinite" begin="-0.052000000000000005s"></animateTransform>
        </g>
      </g>
      <g transform="translate(50 50)">
        <g>
          <circle cx="23" cy="0" r="5" fill="#90e0ff">
            <animate attributeName="r" keyTimes="0;0.5;1" values="9;21;9" dur="1.923076923076923s" repeatCount="indefinite" begin="-0.052000000000000005s"></animate>
          </circle>
          <animateTransform attributeName="transform" type="rotate" keyTimes="0;1" values="0;360" dur="1.923076923076923s" repeatCount="indefinite" begin="-0.078s"></animateTransform>
        </g>
      </g>
      <g transform="translate(50 50)">
        <g>
          <circle cx="23" cy="0" r="5" fill="#f9cf09">
            <animate attributeName="r" keyTimes="0;0.5;1" values="9;21;9" dur="1.5384615384615383s" repeatCount="indefinite" begin="-0.026000000000000002s"></animate>
          </circle>
          <animateTransform attributeName="transform" type="rotate" keyTimes="0;1" values="0;360" dur="1.5384615384615383s" repeatCount="indefinite" begin="-0.10400000000000001s"></animateTransform>
        </g>
      </g>
    </g>
  </svg>
</div>